-- ═══════════════════════════════════════════════════════════════════════════
-- Security hardening
--
-- 1. Receipts become a PRIVATE bucket: financial documents must never be
--    world-readable. Access moves to owner-only storage policies + signed
--    URLs generated by the client at render time.
-- 2. Shared reference data (exchange_rates) becomes read-only for normal
--    users — only trusted server-side processes (service role) may write.
-- 3. Cross-user foreign-key abuse is blocked at the database level: a row
--    owned by user A can no longer reference a category / bank account /
--    recurring rule owned by user B.
-- 4. Rate-snapshot columns get a positive-value CHECK (NOT VALID so the
--    migration never fails on historical rows; new writes are constrained).
-- 5. The SECURITY DEFINER pg_cron helper is no longer executable by clients.
--
-- Every statement is idempotent — safe to re-run against any environment.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Storage: make receipts private, add size/type limits to both buckets
-- ─────────────────────────────────────────────────────────────────────────────

-- Receipts are private financial documents: 10 MiB cap, image types only
-- (matches what ExpenseForm actually uploads via expo-image-picker).
update storage.buckets
set public = false,
    file_size_limit = 10485760, -- 10 MiB
    allowed_mime_types = array[
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/heic',
      'image/heif'
    ]::text[]
where id = 'receipts';

-- World-readable select policy is replaced with an owner-only one. Upload and
-- delete policies (folder-scoped to auth.uid()) are unchanged and stay valid.
drop policy if exists "receipt images are publicly readable" on storage.objects;
drop policy if exists "receipts readable by owner" on storage.objects;
create policy "receipts readable by owner"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'receipts'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );

-- Avatars remain public by design (profile photos are rendered via public URL
-- on every device without an expiring credential), but get the same size cap
-- (2 MiB) and an image-only MIME allowlist so neither bucket accepts arbitrary
-- uploads.
update storage.buckets
set file_size_limit = 2097152, -- 2 MiB
    allowed_mime_types = array[
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/heic',
      'image/heif'
    ]::text[]
where id = 'avatars';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Exchange rates: shared reference data becomes read-only for clients
--
-- Previously every authenticated user could INSERT/UPDATE any (currency, date)
-- row and poison the rates consumed by ALL users. Reads stay open; writes are
-- restricted to the service role (RLS bypassed) — e.g. the backfill script
-- (scripts/backfill-exchange-rates.ts) and future server-side fetchers.
-- ─────────────────────────────────────────────────────────────────────────────

drop policy if exists "exchange rates insertable by authenticated" on public.exchange_rates;
drop policy if exists "exchange rates updatable by authenticated" on public.exchange_rates;
drop policy if exists "exchange rates readable by authenticated" on public.exchange_rates;

create policy "exchange rates readable by authenticated"
  on public.exchange_rates for select
  to authenticated
  using (true);

revoke insert, update, delete on public.exchange_rates from authenticated;
revoke insert, update, delete on public.exchange_rates from anon;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Cross-user reference integrity trigger
--
-- RLS on the child tables only checks auth.uid() = user_id on the child row;
-- it never validated that a referenced category/account/recurring rule belongs
-- to the same user. This BEFORE trigger closes that gap for client-driven
-- writes. Service-role writes (auth.uid() IS NULL — Edge Functions, cron,
-- maintenance scripts) are skipped so trusted server tooling keeps working.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.validate_owned_references()
returns trigger
language plpgsql
as $$
declare
  v_user uuid := new.user_id;
begin
  -- Trusted server-side context (service role): auth.uid() is null there.
  -- Admin tooling may write across users by design; RLS is bypassed for it.
  if auth.uid() is null then
    return new;
  end if;

  if v_user is distinct from auth.uid() then
    raise exception 'SpendFlow ownership check: cannot write a row for another user';
  end if;

  -- Shared check: category must be owned by the authenticated user
  -- (expenses / recurring_rules / category_budget_history).
  if new.category_id is not null then
    if not exists (
      select 1 from public.categories c
      where c.id = new.category_id
        and c.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: category does not belong to you';
    end if;
  end if;

  if tg_table_name = 'expenses' then
    if new.bank_account_id is not null and not exists (
      select 1 from public.bank_accounts b
      where b.id = new.bank_account_id
        and b.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: bank account does not belong to you';
    end if;
    if new.recurring_rule_id is not null and not exists (
      select 1 from public.recurring_rules r
      where r.id = new.recurring_rule_id
        and r.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: recurring rule does not belong to you';
    end if;

  elsif tg_table_name = 'recurring_rules' then
    if new.bank_account_id is not null and not exists (
      select 1 from public.bank_accounts b
      where b.id = new.bank_account_id
        and b.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: bank account does not belong to you';
    end if;

  elsif tg_table_name = 'transfers' then
    if not exists (
      select 1 from public.bank_accounts b
      where b.id = new.from_account_id
        and b.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: source account does not belong to you';
    end if;
    if not exists (
      select 1 from public.bank_accounts b
      where b.id = new.to_account_id
        and b.user_id = auth.uid()
    ) then
      raise exception 'SpendFlow ownership check: destination account does not belong to you';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists expenses_owned_refs on public.expenses;
create trigger expenses_owned_refs
  before insert or update on public.expenses
  for each row execute function public.validate_owned_references();

drop trigger if exists recurring_rules_owned_refs on public.recurring_rules;
create trigger recurring_rules_owned_refs
  before insert or update on public.recurring_rules
  for each row execute function public.validate_owned_references();

drop trigger if exists transfers_owned_refs on public.transfers;
create trigger transfers_owned_refs
  before insert or update on public.transfers
  for each row execute function public.validate_owned_references();

drop trigger if exists category_budget_history_owned_refs on public.category_budget_history;
create trigger category_budget_history_owned_refs
  before insert or update on public.category_budget_history
  for each row execute function public.validate_owned_references();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Monetary snapshot sanity: exchange_rate_to_usd must be positive when set
--    (NOT VALID: constrains new writes without scanning/failing on old rows)
-- ─────────────────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'expenses_exchange_rate_to_usd_positive'
      and conrelid = 'public.expenses'::regclass
  ) then
    alter table public.expenses
      add constraint expenses_exchange_rate_to_usd_positive
      check (exchange_rate_to_usd is null or exchange_rate_to_usd > 0) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'recurring_rules_exchange_rate_to_usd_positive'
      and conrelid = 'public.recurring_rules'::regclass
  ) then
    alter table public.recurring_rules
      add constraint recurring_rules_exchange_rate_to_usd_positive
      check (exchange_rate_to_usd is null or exchange_rate_to_usd > 0) not valid;
  end if;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Lock down the SECURITY DEFINER cron helper. It reads the service-role key
--    from vault and must only be executed by the pg_cron scheduler (which runs
--    as the table owner / postgres), never by anon or authenticated clients.
-- ─────────────────────────────────────────────────────────────────────────────

revoke execute on function public.trigger_fetch_nepal_gold_rate()
  from public, anon, authenticated;
